<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
$namePlugin = '';
if (!empty($this->zoneconfig['conf']['name'])) {
    $namePlugin = ' data-title="' . $this->zoneconfig['conf']['name'] . '"';
}
$data_melisKey = $this->melisKey;

?>

<!-- START melis user tabs -->
<li class="dropdown notification" <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' <?= $namePlugin; ?>>

    <a href="#" class="dropdown-toggle menu-icon dropdown-hover" id="link-to-marketplace" title="<?= $this->translate('tr_melis_link_market_place'); ?>">
        <i class="fa fa-fw fa-download"></i>
        <span class="badge badge-success"><?php if ($this->needToUpdateModuleCount > 0) {
                echo $this->needToUpdateModuleCount;
            } ?></span>
    </a>
    <ul id="module-status" class="dropdown-menu inbox empty-notif">
        <?php if ($this->needToUpdateModuleCount == 0) { ?>
            <li class="empty-notif-li">
                <div class="media">
                    <span><?= $this->translate('tr_melis_module_version_empty'); ?></span>
                </div>
            </li>
        <?php }
        ?>
        <?php if ($this->needToUpdateModuleCount > 0) { ?>
            <?php foreach ($this->modules as $module => $moduleValue) { ?>
                <?php if ($moduleValue['status'] == -1) { ?>
                    <li>
                        <span class="img-circle media-object"></span>
                        <div class="media">
                            <div class="media-body" id="outdated-module-link" data-packageid="<?= $moduleValue['packageId'] ?>" data-packagetitle="<?= $moduleValue['module_name'] ?> ">
                                <i class="fa fa-info-circle"></i>
                                <a class="strong text-primary"><?= $moduleValue['module_name'] ?>
                                    <em class="currentVersion"><?= $moduleValue['currentVersion'] ?> </em></a><span class="time-email"></span>
                                <div class="clearfix"></div><?= $this->translate('tr_melis_market_place_tool_package_module_outdated') ?>
                                <em class="latestVersion"><?= $moduleValue['latestVersion'] ?> </em>
                                <i class="fa fa-download latest-version-icon"></i>
                            </div>
                        </div>
                    </li>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    </ul>
</li>

