<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];


?>
<div data-melisKey="<?= $this->melisKey ?>" id="<?= $this->packageId .'_' . $id; ?>" class="tab-pane container-level-a">
    <div class="innerAll spacing-x2">
        <div class="melis-store">
            <div class="row">
                <div class="col-md-9">
					<div class="row">
                        <div class="col-md-12">
                            <div class="product-summary entry-summary">
                                <h2 class="module-title"><?= $this->package['packageTitle']; ?></h2>
                                <hr>
                            </div>
                        </div>
						<div class="col-md-12">
							<div class="slider slider-single">
                                <?php foreach($this->package['packageImages'] as $images) {
                                    $image = isset($images['imageFile']) ? $images['imageFile'] : '/MelisMarketPlace/images/melis-platform.jpg';
                                ?>
                                    <div>
                                        <img class="img-responsive" src="<?= $image; ?>"
                                             alt="">
                                    </div>
                                <?php
                                }
                                ?>
							</div>
							<div class="slider slider-nav">
                                <?php foreach($this->package['packageImages'] as $images) {
                                $image = isset($images['imageFile']) ? $images['imageFile'] : '/MelisMarketPlace/images/melis-platform.jpg';
                                ?>
								<div>
									<img src="<?= $image; ?>" alt="">
								</div>
                                <?php
                                }
                                ?>
							</div>
						</div>
					</div>
					
					<!-- Tabs -->
	        <div class="widget widget-tabs">
	            <div class="widget-head">
	                <ul>
	                    <li class="active"><a href="#description" data-toggle="tab">Description</a>
	                    </li>
	                    <li><a href="#additionalInfo" data-toggle="tab">Additional Information</a>
	                    </li>
	                </ul>
	            </div>

	            <div class="innerAll">
	                <div class="tab-content">
	                    <div class="tab-pane" id="description">
								<p><?= $this->package['packageDescription']; ?></p>
	                    </div>
	                    <div class="tab-pane" id="additionalInfo">
							<table class="table table-striped push-top">
							    <tbody>
							        <tr>
							            <th>
							                <i class="fa fa-github"></i> <?= $this->translate('tr_market_place_github'); ?>:
							            </th>
							            <td>
                                            <a href="<?= $this->package['packageRepository']; ?>" target="_blank"><?= $this->package['packageRepository']; ?></a>
							            </td>
							        </tr>
							        <tr>
							            <th>
                                            <?= $this->translate('tr_market_place_packagist'); ?>:
							            </th>
							            <td>
                                            <a href="<?= $this->package['packageUrl']; ?>" target="_blank"><?= $this->package['packageUrl']; ?></a>
							            </td>
							        </tr>
							        <tr>
							            <th>
                                            <?= $this->translate('tr_market_place_package_name'); ?>:
							            </th>
							            <td>
                                            <?= $this->package['packageName']; ?>
							            </td>
							        </tr>
                                    <tr>
                                        <th>
                                            <?= $this->translate('tr_market_place_total_downloads'); ?>:
                                        </th>
                                        <td>
                                            <?= number_format($this->package['packageTotalDownloads']); ?>
                                        </td>
                                    </tr>
							    </tbody>
							</table>
	                    </div>
	                </div>
	            </div>
	        </div>

			<hr>

                </div>
                <div class="col-md-3">
                    <aside class="market-sidebar">

                        <div class="melis-marketplace-tags hidden">
                            <h5><?= $this->translate('tr_market_place_tags'); ?></h5>
                            <a href="#"><span class="label label-dark">SEO</span></a>
                            <a href="#"><span class="label label-dark">eCommerce</span></a>
                            <a href="#"><span class="label label-dark">CRM</span></a>
                            <a href="#"><span class="label label-dark">CMS</span></a>
                            <hr class="hr">
                        </div>


                        <h5><?= $this->translate('tr_market_place_most_downloaded_package'); ?></h5>
                        <div id="market-place-most-downloaded-package-list">
                            <ul class="simple-post-list">
                                <?php
                                if(isset($this->packages['packages']) && $this->packages['packages']) {
                                    foreach($this->packages['packages'] as $package) { ?>
                                        <li>
                                            <div class="post-image">
                                                <div class="img-thumbnail">
                                                    <a href="#">
                                                        <?php
                                                        $packageImage = isset($package['packageImages'][0]['imageFile']) ? $package['packageImages'][0]['imageFile'] : '/MelisMarketPlace/images/melis-platform.jpg';
                                                        ?>
                                                        <img alt="" width="60" height="60" class="img-responsive" src="<?= $packageImage; ?>">
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="post-info">
                                                <a href="#"><?= $package['packageTitle']; ?></a>
                                                <p><?= $this->translate('tr_market_place_total_downloads').': '.number_format($package['packageTotalDownloads']); ?></p>
                                                <div class="post-meta"></div>
                                            </div>
                                        </li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>

                    </aside>
                </div>
            </div>    
        </div>
    </div>


    
</div>