<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = $this->zoneconfig['conf']['id'];
}

$form = $this->searchForm;
$packageGroupData = $this->packageGroupData;
?>
<div data-melisKey="<?= $this->melisKey ?>" id="<?= $id; ?>" class="tab-pane container-level-a" data-melispackagistserver="<?= $this->melisPackagistServer; ?>">
    <div class="innerAll spacing-x2">
        <div class="melis-store">
            <div class="row">
                <div class="col-md-9">
                    <div class="melis-store-items">
                        <div class="row">
                            <div class="col-md-9">
                                <div class="store-heading">
                                    <h2 class="content-heading">
                                        <strong><?= $this->translate('tr_market_place'); ?></strong></h2>
                                    <p><?= $this->translate('tr_market_place_subtitle'); ?></p>
                                    <?php if (!$this->isUpdatablePlatform): ?>
                                        <p class="text-danger">
                                            <i class="fa fa-warning"></i> <?= $this->translate('tr_market_place_not_allowed') ?>
                                        </p>
                                    <?php endif ?>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <select class="form-control hidden" name="orderby">
                                    <option value="">Default sorting</option>
                                    <option value="popularity">Sort by popularity</option>
                                    <option value="rating">Sort by average rating</option>
                                    <option value="date">Sort by newness</option>
                                    <option value="price">Sort by price: low to high</option>
                                    <option value="price-desc">Sort by price: high to low</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="input-group">
                                    <?= $this->formRow($form->get('melis_market_place_search_input')); ?>
                                    <span class="input-group-btn">
                                     <button class="btn btn-primary" id="btnMarketPlaceSearch" type="button"><i class="fa fa-search"></i></button>
                                </span>

                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="market-place-btn-filter-group">
                                    <?php
                                    if (isset($packageGroupData)) {
                                        foreach ($packageGroupData as $groupData => $groupValue) {
                                            $typeName = substr($groupValue['mp_group_name'], 5); ?>
                                                <button class='btn btn-primary <?= strtolower($typeName) ?>' data-groupname="<?= $groupValue['mp_group_name'] ?>" value='<?= $groupValue['mp_group_id'] ?>'>
                                                    <div class="melis-svg">
                                                        <svg version="1.1" id="Layer_<?= $groupValue['mp_group_id'] ?>" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                                            <g>
                                                                <rect class="bg-color" y="0.1" fill="#C52127" width="29.9" height="29.9"></rect>
                                                                <rect class="light-color" x="14.6" y="2.7" fill="#E71E26" width="12.7" height="24.6"></rect>
                                                                <g>
                                                                    <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                                                </g>
                                                            </g>
                                                        </svg>
                                                    </div>
                                                    <?= $typeName ?>
                                                </button>
                                        <?php } ?>
                                    <?php } ?>
<!--                                    Add bundles-->
                                    <button class='btn btn-primary bundles pull-right'>
                                        <div class="melis-svg">
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                                    <g>
                                                        <rect class="bg-color" y="0.1" fill="#C52127" width="29.9" height="29.9"></rect>
                                                        <rect class="light-color" x="14.6" y="2.7" fill="#E71E26" width="12.7" height="24.6"></rect>
                                                        <g>
                                                            <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                                        </g>
                                                    </g>
                                                </svg>
                                        </div>
                                        Bundles
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="package-list">
                            <div id="melis-market-place-bundle-list"></div>
                            <div id="melis-market-place-module-list"></div>
                        </div>
                    </div>

                </div>
                <div class="col-md-3">
                    <aside class="market-sidebar">

                        <div class="melis-marketplace-tags hidden">
                            <h5><?= $this->translate('tr_market_place_tags'); ?></h5>
                            <a href="#"><span class="label label-dark">SEO</span></a>
                            <a href="#"><span class="label label-dark">eCommerce</span></a>
                            <a href="#"><span class="label label-dark">CRM</span></a>
                            <a href="#"><span class="label label-dark">CMS</span></a>
                            <hr class="hr">
                        </div>


                        <p><?= $this->translate('tr_market_place_composer_instruction'); ?></p>
                        <hr/>
                        <h5 class="widget-title"><?= $this->translate('tr_market_place_most_downloaded_package'); ?></h5>
                        <div id="market-place-most-downloaded-package-list">
                            <ul class="simple-post-list">
                                <?php
                                if (isset($this->packages['packages']) && $this->packages['packages']) {
                                    foreach ($this->packages['packages'] as $package) { ?>
                                        <li>
                                            <div class="post-image">
                                                <div class="img-thumbnail">
                                                    <a href="#">
                                                        <?php
                                                        $packageImage = isset($package['packageImages'][0]['imageFile']) ? $package['packageImages'][0]['imageFile'] : '/MelisMarketPlace/images/market-placeholder.png';
                                                        ?>
                                                        <img alt="" width="60" height="60" src="<?= $packageImage; ?>">
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="post-info">
                                                <a href="#" class="melis-market-place-view-details" data-packageid="<?= $package['packageId'] ?>" data-packagetitle="<?= $package['packageTitle']; ?>"><?= $package['packageTitle']; ?></a>
                                                <p class="melis-module-downloads">
                                                    <i class="fa fa-download"></i> <?= number_format($package['packageTotalDownloads']); ?>
                                                </p>
                                                <div class="post-meta"></div>
                                            </div>
                                        </li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</div>
