<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];

$form = $this->searchForm;
?>
<div data-melisKey="<?= $this->melisKey ?>" id="<?= $id; ?>" class="tab-pane container-level-a" data-melispackagistserver="<?= $this->melisPackagistServer; ?>">
    <div class="innerAll spacing-x2">
        <div class="melis-store">
            <div class="row">
                <div class="col-md-9">

                    <div class="row">
                        <div class="col-md-9">
                            <h2 class="content-heading"><strong><?= $this->translate('tr_market_place'); ?></strong></h2>
                        </div>
                        <div class="col-md-3">
                            <select class="form-control hidden" name="orderby">
                                <option value="">Default sorting</option>
                                <option value="popularity">Sort by popularity</option>
                                <option value="rating">Sort by average rating</option>
                                <option value="date">Sort by newness</option>
                                <option value="price">Sort by price: low to high</option>
                                <option value="price-desc">Sort by price: high to low</option>
                            </select>
                        </div>
                    </div>

                    <div id="melis-market-place-package-list"></div>
                </div>
                <div class="col-md-3">
                    <aside class="market-sidebar">

                            <div class="input-group">
                                <?= $this->formRow($form->get('melis_market_place_search_input')); ?>
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" id="btnMarketPlaceSearch" type="button"><i class="fa fa-search"></i></button>
                                </span>
                            </div>


                        <hr class="hr">


                        <div class="melis-marketplace-tags hidden">
                            <h5><?= $this->translate('tr_market_place_tags'); ?></h5>
                            <a href="#"><span class="label label-dark">SEO</span></a>
                            <a href="#"><span class="label label-dark">eCommerce</span></a>
                            <a href="#"><span class="label label-dark">CRM</span></a>
                            <a href="#"><span class="label label-dark">CMS</span></a>
                            <hr class="hr">
                        </div>



                        <h5><?= $this->translate('tr_market_place_most_downloaded_package'); ?></h5>
                        <div id="market-place-most-downloaded-package-list">
                            <ul class="simple-post-list">
                                <?php
                                if(isset($this->packages['packages']) && $this->packages['packages']) {
                                    foreach($this->packages['packages'] as $package) { ?>
                                        <li>
                                            <div class="post-image">
                                                <div class="img-thumbnail">
                                                    <a href="#">
                                                        <?php
                                                        $packageImage = isset($package['packageImages'][0]['imageFile']) ? $package['packageImages'][0]['imageFile'] : '/MelisMarketPlace/images/melis-platform.jpg';
                                                        ?>
                                                        <img alt="" width="60" height="60" class="img-responsive" src="<?= $packageImage; ?>">
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="post-info">
                                                <a href="#"><?= $package['packageTitle']; ?></a>
                                                <p><?= $this->translate('tr_market_place_total_downloads').': '.number_format($package['packageTotalDownloads']); ?></p>
                                                <div class="post-meta"></div>
                                            </div>
                                        </li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>    
        </div>
    </div>


    
</div>